/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ITTech
 */

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TitleLbl = new javax.swing.JLabel();
        LargerPromptlbl = new javax.swing.JLabel();
        SmallerPromptlbl = new javax.swing.JLabel();
        PowerPromptlbl = new javax.swing.JLabel();
        RoundDownPromptLbl = new javax.swing.JLabel();
        RoundUpPromptLbl = new javax.swing.JLabel();
        HypotenusePromptLbl = new javax.swing.JLabel();
        Large1Txt = new javax.swing.JTextField();
        Large2Txt = new javax.swing.JTextField();
        Small1Txt = new javax.swing.JTextField();
        Small2Txt = new javax.swing.JTextField();
        BaseTxt = new javax.swing.JTextField();
        ExpTxt = new javax.swing.JTextField();
        Side1Txt = new javax.swing.JTextField();
        Side2Txt = new javax.swing.JTextField();
        RoundUTxt = new javax.swing.JTextField();
        RoundDTxt = new javax.swing.JTextField();
        LargeALbl = new javax.swing.JLabel();
        SmallALbl = new javax.swing.JLabel();
        PowerALbl = new javax.swing.JLabel();
        HypALbl = new javax.swing.JLabel();
        RoundUALbl = new javax.swing.JLabel();
        RoundDALbl = new javax.swing.JLabel();
        LargeBtn = new javax.swing.JButton();
        SmallBtn = new javax.swing.JButton();
        PowerBtn = new javax.swing.JButton();
        HypBtn = new javax.swing.JButton();
        RoundUBtn = new javax.swing.JButton();
        RoundDBtn = new javax.swing.JButton();
        RadiansPromptLbl = new javax.swing.JLabel();
        RootPromptLbl = new javax.swing.JLabel();
        SqrtTxt = new javax.swing.JTextField();
        RadTxt = new javax.swing.JTextField();
        SqrtALbl = new javax.swing.JLabel();
        RadALbl = new javax.swing.JLabel();
        SqrtBtn = new javax.swing.JButton();
        RadiansBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLbl.setText("Math Methods Demonstration");

        LargerPromptlbl.setText("Enter 2 Numbers and click the button,  this program will display the largest of the two numbers");

        SmallerPromptlbl.setText("Enter 2 Numbers and click the button, this program will display the smaller of the two numbers");

        PowerPromptlbl.setText("Enter 2 Numbers and click the button,  this program will display the first number to the power of the second");

        RoundDownPromptLbl.setText("Enter a decimal number and click the button, this program will display the value rounded down to the nearest integers.");

        RoundUpPromptLbl.setText("Enter a decimal number and click the button, this program will display the value rounded up to the nearest integer.");

        HypotenusePromptLbl.setText("Enter 2 side lenghts of a right angle triangle and click the button, this will find the lenght of the hypotenose");

        Small1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Small1TxtActionPerformed(evt);
            }
        });

        LargeALbl.setText("Answer");

        SmallALbl.setText("Answer");

        PowerALbl.setText("Answer");

        HypALbl.setText("Answer");

        RoundUALbl.setText("Answer");

        RoundDALbl.setText("Answer");

        LargeBtn.setText("Calculate");
        LargeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LargeBtnActionPerformed(evt);
            }
        });

        SmallBtn.setText("Calculate");
        SmallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallBtnActionPerformed(evt);
            }
        });

        PowerBtn.setText("Calculate");
        PowerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerBtnActionPerformed(evt);
            }
        });

        HypBtn.setText("Calculate");
        HypBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HypBtnActionPerformed(evt);
            }
        });

        RoundUBtn.setText("Calculate");
        RoundUBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoundUBtnActionPerformed(evt);
            }
        });

        RoundDBtn.setText("Calculate");
        RoundDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoundDBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PowerPromptlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HypotenusePromptLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(ExpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(84, 84, 84)
                                        .addComponent(PowerBtn)
                                        .addGap(48, 48, 48)
                                        .addComponent(PowerALbl))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(Small1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)
                                            .addComponent(Small2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(SmallBtn)
                                            .addGap(54, 54, 54)
                                            .addComponent(SmallALbl))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(Large1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(Large2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(84, 84, 84)
                                            .addComponent(LargeBtn)
                                            .addGap(50, 50, 50)
                                            .addComponent(LargeALbl)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(RoundDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(RoundDBtn)
                                            .addGap(49, 49, 49)
                                            .addComponent(RoundDALbl))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(RoundUTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(RoundUBtn)
                                            .addGap(51, 51, 51)
                                            .addComponent(RoundUALbl))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(Side1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(33, 33, 33)
                                            .addComponent(Side2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(82, 82, 82)
                                            .addComponent(HypBtn)
                                            .addGap(49, 49, 49)
                                            .addComponent(HypALbl))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(TitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(RoundDownPromptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(RoundUpPromptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LargerPromptlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(SmallerPromptlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LargerPromptlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Large1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Large2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LargeALbl)
                    .addComponent(LargeBtn))
                .addGap(24, 24, 24)
                .addComponent(SmallerPromptlbl)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Small1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Small2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SmallALbl))
                    .addComponent(SmallBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(PowerPromptlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PowerALbl)
                    .addComponent(PowerBtn))
                .addGap(6, 6, 6)
                .addComponent(HypotenusePromptLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Side1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Side2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HypALbl)
                    .addComponent(HypBtn))
                .addGap(7, 7, 7)
                .addComponent(RoundUpPromptLbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoundUTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoundUALbl)
                    .addComponent(RoundUBtn))
                .addGap(13, 13, 13)
                .addComponent(RoundDownPromptLbl)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoundDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoundDALbl)
                    .addComponent(RoundDBtn)))
        );

        RadiansPromptLbl.setText("Enter an angle in degrees, this program will display the angle in radians.");

        RootPromptLbl.setText("Enter an integer and click the button, this program will display the square root of the number.");

        SqrtALbl.setText("Answer");

        RadALbl.setText("Answer");

        SqrtBtn.setText("Calculate");
        SqrtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SqrtBtnActionPerformed(evt);
            }
        });

        RadiansBtn.setText("Calculate");
        RadiansBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadiansBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(RadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RadiansBtn)
                            .addGap(48, 48, 48)
                            .addComponent(RadALbl))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(SqrtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(178, 178, 178)
                            .addComponent(SqrtBtn)
                            .addGap(46, 46, 46)
                            .addComponent(SqrtALbl)))
                    .addComponent(RootPromptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadiansPromptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RootPromptLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SqrtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SqrtALbl)
                    .addComponent(SqrtBtn))
                .addGap(18, 18, 18)
                .addComponent(RadiansPromptLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadALbl)
                    .addComponent(RadiansBtn))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Small1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Small1TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Small1TxtActionPerformed

    private void LargeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LargeBtnActionPerformed

        int num1; //Variable Declaration Area
        int num2;
        
        num1 = Integer.parseInt(Large1Txt.getText()); //Getting input from user
        num2 = Integer.parseInt(Large2Txt.getText());
        LargeALbl.setText(String.valueOf(Math.max(num1, num2)));
        //Determines the larger of the inputs, then outputs this to the user
    }//GEN-LAST:event_LargeBtnActionPerformed

    private void SmallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallBtnActionPerformed
        int num1; //Variable Declaration Area
        int num2;
        
        num1 = Integer.parseInt(Small1Txt.getText()); //Getting input from user
        num2 = Integer.parseInt(Small2Txt.getText());
        SmallALbl.setText(String.valueOf(Math.min(num1, num2)));
        //Determines which number is the smaller one, then outputs this to the user
    }//GEN-LAST:event_SmallBtnActionPerformed

    private void PowerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerBtnActionPerformed
        int num1; //Variable Declaration Area
        int num2;
        
        num1 = Integer.parseInt(BaseTxt.getText()); //Getting input from user
        num2 = Integer.parseInt(ExpTxt.getText());
        PowerALbl.setText(String.valueOf(Math.pow(num1, num2)));
        // Calculates the power of a base and a exponent, converts the value to a string then outputs to the user
    }//GEN-LAST:event_PowerBtnActionPerformed

    private void HypBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HypBtnActionPerformed
        int num1; //Variable Declaration Area
        int num2;
        
        num1 = Integer.parseInt(Side1Txt.getText()); //Getting input from user
        num2 = Integer.parseInt(Side2Txt.getText());
        HypALbl.setText(String.valueOf(Math.hypot(num1, num2)));
        //Using the pythogorean theorem, calculates magnitude of the hyptonuse, converts this to a string, then outputs to the user
    }//GEN-LAST:event_HypBtnActionPerformed

    private void RoundUBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoundUBtnActionPerformed
        double num1; //Variable Declaration Area
        
        num1 = Double.parseDouble(RoundUTxt.getText()); //Getting input from user
        // Rounds up the number, then converts the double to a String, then outputting to the user
        RoundUALbl.setText(String.valueOf(Math.ceil(num1)));
    }//GEN-LAST:event_RoundUBtnActionPerformed

    private void RoundDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoundDBtnActionPerformed
        double num1; //Variable Declaration Area
        
        num1 = Double.parseDouble(RoundDTxt.getText()); //Getting input from user
        //Rounds down the number, then converts the double to a String, then outputting to the user
        RoundDALbl.setText(String.valueOf(Math.floor(num1)));
    }//GEN-LAST:event_RoundDBtnActionPerformed

    private void SqrtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SqrtBtnActionPerformed
        double num1; //Variable Declaration Area
        
        num1 = Double.parseDouble(SqrtTxt.getText()); //Getting input from user
        //Calculates the square root of the int, then the double to a String, then outputting to the user
        SqrtALbl.setText(String.valueOf(Math.sqrt(num1)));
    }//GEN-LAST:event_SqrtBtnActionPerformed

    private void RadiansBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadiansBtnActionPerformed
        double num1; //Variable Declaration Area
        
        num1 = Double.parseDouble(RadTxt.getText()); //Getting input from user
        //Converting Degrees to Radians, then the double to a String, then outputting to the user
        RadALbl.setText(String.valueOf(Math.toRadians(num1)));
    }//GEN-LAST:event_RadiansBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BaseTxt;
    private javax.swing.JTextField ExpTxt;
    private javax.swing.JLabel HypALbl;
    private javax.swing.JButton HypBtn;
    private javax.swing.JLabel HypotenusePromptLbl;
    private javax.swing.JTextField Large1Txt;
    private javax.swing.JTextField Large2Txt;
    private javax.swing.JLabel LargeALbl;
    private javax.swing.JButton LargeBtn;
    private javax.swing.JLabel LargerPromptlbl;
    private javax.swing.JLabel PowerALbl;
    private javax.swing.JButton PowerBtn;
    private javax.swing.JLabel PowerPromptlbl;
    private javax.swing.JLabel RadALbl;
    private javax.swing.JTextField RadTxt;
    private javax.swing.JButton RadiansBtn;
    private javax.swing.JLabel RadiansPromptLbl;
    private javax.swing.JLabel RootPromptLbl;
    private javax.swing.JLabel RoundDALbl;
    private javax.swing.JButton RoundDBtn;
    private javax.swing.JTextField RoundDTxt;
    private javax.swing.JLabel RoundDownPromptLbl;
    private javax.swing.JLabel RoundUALbl;
    private javax.swing.JButton RoundUBtn;
    private javax.swing.JTextField RoundUTxt;
    private javax.swing.JLabel RoundUpPromptLbl;
    private javax.swing.JTextField Side1Txt;
    private javax.swing.JTextField Side2Txt;
    private javax.swing.JTextField Small1Txt;
    private javax.swing.JTextField Small2Txt;
    private javax.swing.JLabel SmallALbl;
    private javax.swing.JButton SmallBtn;
    private javax.swing.JLabel SmallerPromptlbl;
    private javax.swing.JLabel SqrtALbl;
    private javax.swing.JButton SqrtBtn;
    private javax.swing.JTextField SqrtTxt;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
